In [205]:
import tensorflow as tf
import numpy as np
from tensorflow import keras
import matplotlib.pyplot as plt

class myCallback(keras.callbacks.Callback):
    def on_epoch_end(self,epoch,logs={}):
        if(logs.get("loss") < 0.4):
            print("\nloss is low so cancelling training!")
            self.model.stop_training = True




callbacks = myCallback()

fashion_mnist = keras.datasets.fashion_mnist
(train_images,train_labels),(test_images,test_labels) = fashion_mnist.load_data()


# 建立模型
model = keras.Sequential()
model.add(keras.layers.Conv2D(64,(3,3),activation="relu",input_shape=(28,28,1)))
model.add(keras.layers.MaxPooling2D(2,2))
model.add(keras.layers.Conv2D(64,(3,3),activation="relu"))
model.add(keras.layers.MaxPooling2D(2,2))
model.add(keras.layers.Flatten(input_shape=(28,28)))
model.add(keras.layers.Dense(128,activation=tf.nn.relu))
model.add(keras.layers.Dense(10,activation=tf.nn.softmax))

model.compile(optimizer=tf.optimizers.Adam(),loss=tf.losses.sparse_categorical_crossentropy,metrics=['accuracy'])

train_images = train_images/255
model.fit(train_images.reshape(-1,28,28,1),train_labels,epochs=10,callbacks=[callbacks])

print(train_images.reshape(-1,28,28,1))
test_images_scaled = test_images/255
# model.evaluate(test_images_scaled.reshape(-1,28,28,1),test_labels)

# 查看单张图片的属于哪一类
#print(test_images[5].shape)
# print(test_image.shape)
# demo = tf.reshape(test_images[30],(1,28,28))
# model.predict(demo)

Epoch 1/10
1875/1875 [==============================] - 58s 30ms/step - loss: 0.4486 - accuracy: 0.8362
Epoch 2/10
1875/1875 [==============================] - 38s 20ms/step - loss: 0.2938 - accuracy: 0.8914

loss is low so cancelling training!
[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.